### ISSUE TITLE
Constant function argument

### ISSUE THREAD

**Issue by yxliang01** [ethereum/solc-js#106]
So, I was creating a contract with functions that has arguments declared constant. Solc gives me `abort(5)` (I used it via browser solidity). I am not sure whether this is supported in solidity. But, if not, an understandable should be given.

The okay one
```js
contract Hi {
    function addOne(uint a) constant returns (uint) {
        return a + 1;
    }
}
```
The one gives `abort(5)`
```js
contract Hi {
    function addOne(uint constant a) constant returns (uint) {
        return a + 1;
    }
}
```

Thanks

**Comment by axic** [comment]
This was the same bug as #113.

With an old verison:
```
$ solcjs --version
0.3.6
$ solcjs --bin _c.sol 
16
16

/usr/local/lib/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&filenam
abort(16) at Error
    at jsStackTrace (/usr/local/lib/node_modules/solc/soljson.js:1:19718)
    at stackTrace (/usr/local/lib/node_modules/solc/soljson.js:1:19901)
    at abort (/usr/local/lib/node_modules/solc/soljson.js:18:13722)
    at Array.aIb (/usr/local/lib/node_modules/solc/soljson.js:5:1134653)
    at Array.gma (/usr/local/lib/node_modules/solc/soljson.js:7:2115)
    at Object.gHb [as dynCall_viiii] (/usr/local/lib/node_modules/solc/soljson.js:5:1131596)
    at invoke_viiii (/usr/local/lib/node_modules/solc/soljson.js:1:1268572)
    at Array.kia (/usr/local/lib/node_modules/solc/soljson.js:8:787848)
    at Array.Bda (/usr/local/lib/node_modules/solc/soljson.js:8:307414)
    at Object.Zyb [as dynCall_vii] (/usr/local/lib/node_modules/solc/soljson.js:5:1091836)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

It was fixed with the last two releases:
```
 ./solcjs --bin _c.sol 
_c.sol:1:1: Warning: Source file does not specify required compiler version!Consider adding "pragma solidity ^0.4.13
contract Hi {
^
Spanning multiple lines.

_c.sol:2:21: TypeError: Illegal use of "constant" specifier.
    function addOne(uint constant a) constant returns (uint) {
                    ^-------------^

_c.sol:2:21: TypeError: Uninitialized "constant" variable.
    function addOne(uint constant a) constant returns (uint) {
                    ^-------------^

```
