### ISSUE TITLE
`require('solc')` causes `ELIFECYCLE`

### ISSUE THREAD

**Issue by rudolph9** [ethereum/solc-js#164]
```
$ node
> require('solc')
Killed
$ node --version
v6.11.5
$ npm --version
3.10.10
$ cat npm-shrinkwrap.json | grep solc
    "solc": {
      "resolved": "https://registry.npmjs.org/solc/-/solc-0.4.18.tgz",
```

The detailed log when I start my server `npm start` which dies at `require('solc'):

```
:!cat something
0 info it worked if it ends with ok
1 verbose cli [ '/home/user/.nvm/versions/node/v6.11.5/bin/node',
1 verbose cli   '/home/user/.nvm/versions/node/v6.11.5/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle project@1.0.0~prestart: project@1.0.0
6 silly lifecycle project@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle project@1.0.0~start: project@1.0.0
8 verbose lifecycle project@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle project@1.0.0~start: PATH: /home/user/.nvm/versions/node/v6.11.5/lib/node_modules/npm/bin/node-gyp-bin:/home/user/project/project/node_modules/.bin:/home/user/.nvm/versions/node/v6.11.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle project@1.0.0~start: CWD: /home/user/project/project
11 silly lifecycle project@1.0.0~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle project@1.0.0~start: Returned: code: 137  signal: null
13 info lifecycle project@1.0.0~start: Failed to exec start script
14 verbose stack Error: project@1.0.0 start: `node server.js`
14 verbose stack Exit status 137
14 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v6.11.5/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v6.11.5/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid project@1.0.0
16 verbose cwd /home/user/project/project
17 error Linux 4.4.0-101-generic
18 error argv "/home/user/.nvm/versions/node/v6.11.5/bin/node" "/home/user/.nvm/versions/node/v6.11.5/bin/npm" "start"
19 error node v6.11.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error project@1.0.0 start: `node server.js`
22 error Exit status 137
23 error Failed at the project@1.0.0 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the project package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs project
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls project
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by axic** [comment]
This doesn't seem like an issue with solc-js. I think you might be running out of memory. By any chance is this being run on AWS?

**Comment by rudolph9** [comment]
It's running on digital ocean and the OS has 1GB allocated.  I suspected memory too but after quitting everything except for system processes and increasing the memory to 1GB I didn't know what to think.

**Comment by sachintandon** [comment]
Check the number of CPU processors. i was facing the same issue increased memory to 3 GB and CPU to 2 core CPU and it worked,

**Comment by axic** [comment]
It seems that this was a memory size issue.
