### ISSUE TITLE
NO_DYNAMIC_EXECUTION was set, cannot eval - ccall/cwrap are not functional

### ISSUE THREAD

**Issue by LogvinovLeon** [ethereum/solc-js#321]
Hi. I'm using `solcjs` to compile solidity project and it was working fine with all the ^0.4.0 versions. Now I want to try solidity 0.5.0 versions and I'm getting this error message:
```
NO_DYNAMIC_EXECUTION was set, cannot eval - ccall/cwrap are not functional
```
I've looked through the issues but wasn't able to figure it out. Do you have any idea how to fix it? Seems emscripten related.
```
NO_DYNAMIC_EXECUTION was set, cannot eval - ccall/cwrap are not functional
abort("NO_DYNAMIC_EXECUTION was set, cannot eval - ccall/cwrap are not functional") at Error
    at jsStackTrace (/Users/leonidlogvinov/Dev/0x/0x-monorepo/packages/sol-compiler/solc_bin/soljson-v0.5.0+commit.1d4f565a.js:1:19656)
    at stackTrace (/Users/leonidlogvinov/Dev/0x/0x-monorepo/packages/sol-compiler/solc_bin/soljson-v0.5.0+commit.1d4f565a.js:1:19839)
    at abort (/Users/leonidlogvinov/Dev/0x/0x-monorepo/packages/sol-compiler/solc_bin/soljson-v0.5.0+commit.1d4f565a.js:20:13296)
    at getCFunc (/Users/leonidlogvinov/Dev/0x/0x-monorepo/packages/sol-compiler/solc_bin/soljson-v0.5.0+commit.1d4f565a.js:1:7278)
    at ccallFunc (/Users/leonidlogvinov/Dev/0x/0x-monorepo/packages/sol-compiler/solc_bin/soljson-v0.5.0+commit.1d4f565a.js:1:8028)
    at /Users/leonidlogvinov/Dev/0x/0x-monorepo/packages/sol-compiler/solc_bin/soljson-v0.5.0+commit.1d4f565a.js:1:8564
    at Object.compile (/Users/leonidlogvinov/Dev/0x/0x-monorepo/packages/sol-compiler/node_modules/solc/wrapper.js:77:16)
    at Compiler._compile (/Users/leonidlogvinov/Dev/0x/0x-monorepo/packages/sol-compiler/src/compiler.ts:423:26)
    at Compiler.<anonymous> (/Users/leonidlogvinov/Dev/0x/0x-monorepo/packages/sol-compiler/src/compiler.ts:250:41)
    at step (/Users/leonidlogvinov/Dev/0x/0x-monorepo/packages/sol-compiler/lib/src/compiler.js:43:23)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by axic** [comment]
Is this a release of 0.5.x ? It seems to be working on the CI here as well as locally. What is the Javascript interface you are using?

**Comment by LogvinovLeon** [comment]
Yes. I see that with both `0.5.0` and `0.5.1` versions. I'm using the `compile` function. I can create a repro brunch for you later.

**Comment by pieterhartel** [comment]
Same problem here. Is there a solution?

--pieter

**Comment by chriseth** [comment]
@LogvinovLeon which version of nodejs are you using?

**Comment by LogvinovLeon** [comment]
I'm using latest LTS release Dubnium v10.14.2.

**Comment by axic** [comment]
@LogvinovLeon thanks for investigating! Maybe we should document this in the readme.

**Comment by hefeleal** [comment]
Thanks a lot @LogvinovLeon Updating the `package.json` file fixed my issue as well :+1:
