### ISSUE TITLE
Error: Cannot find module './smtchecker.js'

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/solc-js#324]
When installing `solc` globally, it got installed successfully. But when we try to use it, it throws following error : 
```
$ solcjs --help
module.js:549
    throw err;
    ^

Error: Cannot find module './smtchecker.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/solc/solcjs:9:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
 Seems it doesn't pass the `smtchecker.js`. When i add that file manually after copying from github. It worked !
Also while installing locally, it works fine.
**OS:** ubuntu 16.04 LTS

**Comment by axic** [comment]
This was fixed in #314 and will be released soon.
