### ISSUE TITLE
Solc Compiler related Error in Nodejs

### ISSUE THREAD

**Issue by saarshah** [ethereum/solc-js#423]
I have almost 800 .solc files of version ^0.5.12 (i am using also 0.5.13 compiler version), when i all give them to my input, to compile with following code;

```
var walk = function (dir) {
    var results = [];
    var list = fs.readdirSync(dir);
    list.forEach(function (file) {
        file = dir + '/' + file;
        var stat = fs.statSync(file);
        if (stat && stat.isDirectory()) {
            results = results.concat(walk(file));
        } else {
            if (file.substr(file.length - 4, file.length) === ".sol") {
                sources = {
                    ...sources,
                    [file]: {
                        content: getContractSource(file)

                    }
                };
            }

            results.push(file);

        }
    });

    return results;
};

walk(sourceFolderPath);


const input = {
    language: 'Solidity',
    sources,
    settings: {
        outputSelection: {
            '*': {
                '*': ['*']
            }
        }
    }
}

console.log('\nCompiling contracts...');
const output = JSON.parse(solc.compile(JSON.stringify(input)));
let shouldBuild = true;

if (output.errors) {
    console.error(output.errors);
    // throw '\nError in compilation please check the contract\n';
    for (error of output.errors) {
        if (error.severity === 'error') {
            shouldBuild = false;
            throw 'Error found';
            break;
        }
    }
}

if (shouldBuild) {
    console.log('\nBuilding please wait...');

    fs.removeSync(buildFolderPath);
    fs.ensureDirSync(buildFolderPath);

    for (let contractFile in output.contracts) {
        for (let key in output.contracts[contractFile]) {
            var c = contractFile.substr(40,contractFile.length-4)
            if(c.search(key)==0) {

            fs.outputJsonSync(
                path.resolve(buildFolderPath, `${key}.json`),
                {
                    abi: output.contracts[contractFile][key]["abi"],
                    bytecode: output.contracts[contractFile][key]["evm"]["bytecode"]["object"]
                },
                {
                    spaces: 2,
                    EOL: "\n"
                }
            );
        }
        }
    }
    console.log('Build finished successfully!\n');
} else {
    console.log('\nBuild failed\n');
}
```
its gives following error;

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Users\aa\Desktop\temp\compile.js:58:21)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```
However, if i give them less number of files (say 400) , then the same code gives following error;

```
[
  {
    type: 'JSONError',
    component: 'general',
    severity: 'error',
    message: 'Error parsing input JSON.'
  }
]
```
and when i give it more less then following error occurred;

```
[
  {
    component: 'general',
    formattedMessage: '* Line 1, Column 1\n' +
      '  Syntax error: value, object or array expected.\n' +
      '* Line 1, Column 2\n' +
      '  Extra non-whitespace after JSON value.\n',
    message: '* Line 1, Column 1\n' +
      '  Syntax error: value, object or array expected.\n' +
      '* Line 1, Column 2\n' +
      '  Extra non-whitespace after JSON value.\n',
    severity: 'error',
    type: 'JSONError'
  }
]
```
If i give less number of files (may be size less then 1 MB), then my code works well.... I am not sure , whether its bug of solc compiler or JSON bug ?

**Comment by matheusaaguiar** [comment]
Closing this for inactivity and also the situation is not clearly related.
