### ISSUE TITLE
"Cannot find module 'solc'" Error while i was trying to execute a simple nodejs code using 'solc' module.

### ISSUE THREAD

**Issue by piyushshende** [ethereum/solc-js#491]
this is my simple source code of nodejs:-

const path = require('path');
const fs = require('fs');
const solc = require('solc');

const inboxPath = path.resolve(__dirname, 'contracts', 'Inbox.sol');
const source = fs.readFileSync(inboxPath, 'utf8');

console.log(solc.compile(source, 1));

and i'm getting this type of error:-
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'solc'
Require stack:
- f:\Inbox project directory\compile.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (f:\Inbox project directory\compile.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'f:\\Inbox project directory\\compile.js' ]
}

I also install solc by using command "npm install -g solc" but dosn't work.

**Comment by chriseth** [comment]
Maybe related to https://github.com/ethereum/solc-js/issues/34

**Comment by chriseth** [comment]
Does it help if you install it locally through a package.json?

**Comment by S1CKMYDUCK** [comment]
Same error, I could not rectify it.

**Comment by BigB97** [comment]
I think it has to do with the version, I had to uninstall the current version 

- npm uninstall solc
- npm install --save solc@0.4.25

**Comment by matheusaaguiar** [comment]
Closing this as it is not reproducible anymore.
