### ISSUE TITLE
solcjs does not provide import callback suitable for command-line use

### ISSUE THREAD

**Issue by john17797** [ethereum/solc-js#522]
I was trying to compile a .sol file using **solcjs --standardjson inputConfig.json** command, the compilation had thrown error. But when I try with Solidity compiler, the compilation was success. 
 
Can you please instruct me to compile with  **solcjs --standardjson** command?

_My inputConfig.json content is_
```
{"language": "Solidity",
  "sources":
  {
    "testEth.sol":
    {
      "urls":[
           "E:\Solidity\testEth\testEth\testEth.sol"
		   ]
    }
  },
  "settings":
  {
    "optimizer": {
      "enabled": true
    },
    "evmVersion": "byzantium",
    "outputSelection": {
      "*": {
        "*": [ 
          "abi", "evm.bytecode"
        ]
      }
    }
  }
}	
```
_Following texts are the error message had thrown:_
**fs.js:193
  let mode = stats[1];
                  ^

TypeError: Cannot read property '1' of undefined
    at isFileType (fs.js:193:19)
    at Object.readFileSync (fs.js:380:16)
    at Object.<anonymous> (C:\Users\john\AppData\Roaming\npm\node_modules\solc\solcjs:60:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47**

**Comment by christianparpart** [comment]
> I was trying to compile a .sol file using **solcjs --standardjson inputConfig.json** command, the compilation had thrown error. But when I try with Solidity compiler, the compilation was success.
> 
> Can you please instruct me to compile with **solcjs --standardjson** command?

```sh
solcjs --standard-json < inputConfig.json
```
I think you should pass the standard JSON configuration via `stdin` (standard input).  Did you try that already, @john17797 ?

Mind the `<` in front of the `inputConfig.json` for redirecting that file into `stdin` and (maybe just a typo) the solcjs CLI parameter is `--standard-json` (with a dash).

**Comment by christianparpart** [comment]
@john17797 I am soft-closing due to inactivity. Please just ask if you need any help, for example in https://gitter.im/ethereum/solidity :).

**Comment by john17797** [comment]
@christianparpart Still I'm facing an another issue. I have executed command with **--standard-json** and the Input JSON file. 
Please check the content of my input JSON file:
`{"language": "Solidity",
  "sources":
  {
    "Ballot.sol":
    {
      "urls":[
           "Ballot.sol"
		   ]
    }
  },
  "settings":
  {
    "optimizer": {
      "enabled": true
    },
    "evmVersion": "byzantium",
    "outputSelection": {
      "*": {
        "*": [ 
          "abi","evm.bytecode.object"
        ]
      }
    }
  }
}	
`
Command which I have executed on Linux server: `solcjs --standard-json < /home0/admin/GOPATH/src/Ballot/inputConfig.json`
and the response for the above command is: 
`{"errors":[{"component":"general","formattedMessage":"Cannot import url (\"Ballot.sol\"): File import callback not supported","message":"Cannot import url (\"Ballot.sol\"): File import callback not supported","severity":"error","type":"IOError"}],"sources":{}}`

@christianparpart **Cannot import url (\"Ballot.sol\"): File import callback not supported","message":"Cannot import url (\"Ballot.sol\"): File import callback not supported** -- This is error which I have got for the above execution. Please check my inputJSON file content and let me know if any changes required ASAP or anything should we need to enable **solcjs --standard-json**

Absolute path of my solidity file: **/home0/admin/GOPATH/src/Ballot/Ballot.sol**
![inputJSON](https://user-images.githubusercontent.com/50577110/116661667-72c94d00-a9b2-11eb-9189-08150dcff6f9.PNG)

**Comment by cameel** [comment]
@john17797 I think you have found one case where the `solcjs` script is not a drop-in replacement for `solc`. `solc` is by design meant for command-line use and has a built-in import callback that looks for the file on disk if it's not available in JSON. `solc-js` library, on the other hand, when used from JavaScript requires user to provide this callback as a piece of JavaScript code (see https://github.com/ethereum/solc-js#example-usage-with-import-callback). This is because it could be running in an environment where there is no access to the filesystem (e.g. in the browser) and it's the responsibility of the code using it to provide some way to access files. For example Remix IDE uses this mechanism to store files in your browser's local storage and also allows you to import directly from github (while `solc` does not).

The `solcjs` script is just a wrapper over the `solc-js` library and apparently does not by itself provide any callback. @chriseth @christianparpart I don't think it's a bug but rather a design question - should we provide a callback matching `solc` so that both work the same way on the command line?

In your particular case you have to include the whole content of the file in the JSON if you want it to work with `solcjs` script:

```json
{
    "language": "Solidity",
    "sources": {
        "Ballot.sol": {
            "content": "pragma solidity ^0.4.22;\\n\\n/// @title Voting with delegation.\\ncontract Ballot {\\n    // This declares a new complex type which will\\n    // be used for variables later.\\n    // It will represent a single voter.\\n    struct Voter {\\n        uint weight; // weight is accumulated by delegation\\n        bool voted;  // if true, that person already voted\\n        address delegate; // person delegated to\\n        uint vote;   // index of the voted proposal\\n    }\\n\\n    // This is a type for a single proposal.\\n    struct Proposal {\\n        bytes32 name;   // short name (up to 32 bytes)\\n        uint voteCount; // number of accumulated votes\\n    }\\n\\n    address public chairperson;\\n\\n    // This declares a state variable that\\n    // stores a `Voter` struct for each possible address.\\n    mapping(address => Voter) public voters;\\n\\n    // A dynamically-sized array of `Proposal` structs.\\n    Proposal[] public proposals;\\n\\n    /// Create a new ballot to choose one of `proposalNames`.\\n    constructor(bytes32[] proposalNames) public {\\n        chairperson = msg.sender;\\n        voters[chairperson].weight = 1;\\n\\n        // For each of the provided proposal names,\\n        // create a new proposal object and add it\\n        // to the end of the array.\\n        for (uint i = 0; i < proposalNames.length; i++) {\\n            // `Proposal({...})` creates a temporary\\n            // Proposal object and `proposals.push(...)`\\n            // appends it to the end of `proposals`.\\n            proposals.push(Proposal({\\n                name: proposalNames[i],\\n                voteCount: 0\\n            }));\\n        }\\n    }\\n\\n    // Give `voter` the right to vote on this ballot.\\n    // May only be called by `chairperson`.\\n    function giveRightToVote(address voter) public {\\n        // If the first argument of `require` evaluates\\n        // to `false`, execution terminates and all\\n        // changes to the state and to Ether balances\\n        // are reverted.\\n        // This used to consume all gas in old EVM versions, but\\n        // not anymore.\\n        // It is often a good idea to use `require` to check if\\n        // functions are called correctly.\\n        // As a second argument, you can also provide an\\n        // explanation about what went wrong.\\n        require(\\n            msg.sender == chairperson,\\n            \\"Only chairperson can give right to vote.\\"\\n        );\\n        require(\\n            !voters[voter].voted,\\n            \\"The voter already voted.\\"\\n        );\\n        require(voters[voter].weight == 0);\\n        voters[voter].weight = 1;\\n    }\\n\\n    /// Delegate your vote to the voter `to`.\\n    function delegate(address to) public {\\n        // assigns reference\\n        Voter storage sender = voters[msg.sender];\\n        require(!sender.voted, \\"You already voted.\\");\\n\\n        require(to != msg.sender, \\"Self-delegation is disallowed.\\");\\n\\n        // Forward the delegation as long as\\n        // `to` also delegated.\\n        // In general, such loops are very dangerous,\\n        // because if they run too long, they might\\n        // need more gas than is available in a block.\\n        // In this case, the delegation will not be executed,\\n        // but in other situations, such loops might\\n        // cause a contract to get \\"stuck\\" completely.\\n        while (voters[to].delegate != address(0)) {\\n            to = voters[to].delegate;\\n\\n            // We found a loop in the delegation, not allowed.\\n            require(to != msg.sender, \\"Found loop in delegation.\\");\\n        }\\n\\n        // Since `sender` is a reference, this\\n        // modifies `voters[msg.sender].voted`\\n        sender.voted = true;\\n        sender.delegate = to;\\n        Voter storage delegate_ = voters[to];\\n        if (delegate_.voted) {\\n            // If the delegate already voted,\\n            // directly add to the number of votes\\n            proposals[delegate_.vote].voteCount += sender.weight;\\n        } else {\\n            // If the delegate did not vote yet,\\n            // add to her weight.\\n            delegate_.weight += sender.weight;\\n        }\\n    }\\n\\n    /// Give your vote (including votes delegated to you)\\n    /// to proposal `proposals[proposal].name`.\\n    function vote(uint proposal) public {\\n        Voter storage sender = voters[msg.sender];\\n        require(!sender.voted, \\"Already voted.\\");\\n        sender.voted = true;\\n        sender.vote = proposal;\\n\\n        // If `proposal` is out of the range of the array,\\n        // this will throw automatically and revert all\\n        // changes.\\n        proposals[proposal].voteCount += sender.weight;\\n    }\\n\\n    /// @dev Computes the winning proposal taking all\\n    /// previous votes into account.\\n    function winningProposal() public view\\n            returns (uint winningProposal_)\\n    {\\n        uint winningVoteCount = 0;\\n        for (uint p = 0; p < proposals.length; p++) {\\n            if (proposals[p].voteCount > winningVoteCount) {\\n                winningVoteCount = proposals[p].voteCount;\\n                winningProposal_ = p;\\n            }\\n        }\\n    }\\n\\n    // Calls winningProposal() function to get the index\\n    // of the winner contained in the proposals array and then\\n    // returns the name of the winner\\n    function winnerName() public view\\n            returns (bytes32 winnerName_)\\n    {\\n        winnerName_ = proposals[winningProposal()].name;\\n    }\\n}\\n"
        }
    },
    "settings": {
        "optimizer": {
            "enabled": true
        },
        "evmVersion": "byzantium",
        "outputSelection": {
            "*": {
                "*": [
                    "abi",
                    "evm.bytecode.object"
                ]
            }
        }
    }
}
```

**Comment by cameel** [comment]
Just a correction. I looked at the source and `solcjs` does actually have a callback. It just does not use it if you do not provide the `--base-path` option. So something like this should work for you:

```bash
solcjs --standard-json --base-path . < input.json
```

So this is apparently by design. I think it should be explained somewhere though.

**Comment by john17797** [comment]
@cameel I have tried the command which you have shared. Here the `--base-path` option does not support by `solcjs`. input.json file with **content** option works and it returns valid errors in the **.sol** files. 

Can't we directly give the file name or path rather than the file content into the input JSON? I have shared the error response of the file and check that the `--base-path` does not support
![github](https://user-images.githubusercontent.com/50577110/116771505-a61ae300-aa69-11eb-9eff-452163570506.PNG)
 by `solcjs`.

**Comment by cameel** [comment]
Are you using the latest version of `solc-js`? The `--base-path` option was added in `solc-js` 0.6.9 (#471) so if you are using an earlier version, it won't work.

Note that the latest `solc-js` works with any older version of the compiler so you can use it even if you want to compile with solc 0.4.22 (as your code suggests). You can just download solc 0.4.22 and use it to replace the default `soljson.js` in `solc-js` directory:
```bash
curl --output soljson.js https://binaries.soliditylang.org/emscripten-wasm32/solc-emscripten-wasm32-v0.4.22+commit.4cb486ee.js
```

I tried it on my system and it works just fine with your files:
```bash
./solcjs --standard-json --base-path . < inputConfig.sol
```

Output (truncated):
```json
{"contracts":{"Ballot.sol":{"Ballot":{"abi":[{"constant":false,"inputs":[{"name":"proposal","type":"uint256"}],"name":"vote","outputs": 
```

**Comment by john17797** [comment]
@cameel I have upgraded my solcjs version and now it's working fine. Thanks for your help. I'll reach out you if I have any doubts in solcjs compiler.
