### ISSUE TITLE
Making compileJSONCallback work

### ISSUE THREAD

**Issue by axic** [ethereum/solc-js#6]
**Intro for anyone trying to understand the context:**

Basically `compileJSONCallback` uses the same interface as `compileJSONMulti` (which supports multiple input files defined in a JSON) with the addition of a `readFileCallback` parameter.

This callback is executed when a missing import statement is encountered. It receives the import path and should return the destination file contents. To be more precise it expects an array with two fields: `contents` and `error`.

Internally this is [wrapped to match](https://github.com/ethereum/solc-js/blob/master/index.js#L22) the `readFileCallback(path, contents, error)` method ([see in C](https://github.com/ethereum/solidity/blob/develop/solc/jsonCompiler.cpp#L49)). It has an Emscripten-wrapping, therefore all parameters are pointers to the Emscripten heap. ([relevant Emscripten doc](http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code-call-function-pointers-from-c))

Now in C world we have a [condition](https://github.com/ethereum/solidity/blob/develop/solc/jsonCompiler.cpp#L142) to display an error if both `contents` and `error` are null (i.e. JS didn't touched them).  Otherwise they are copied around appropriately.

**Problem:**

The wrapped callback is executed as evidenced by a `console.log` within, but no matter what is done, upon returning from this callback nothing happens. 

If the callback doesn't touches the `contents`/`error`, they should remain null and the error as mentioned above should be displayed.

Sample code to test:
```
var cb = soljson.Runtime.addFunction(function() { console.log('We should trigger the error') });
var output = compileInternal(input, optimize, cb);
console.log(output);
```

```
bash-3.2$ node test.js 
We should trigger the error
bash-3.2$ 
```

The only way I can get a different result is by setting the pointer to a wrong location: `soljson.setValue(ptr, ptr, '*')`:

```
/Users/alex/Projects/solc/solc-js/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_W
abort() at Error
    at jsStackTrace (/Users/alex/Projects/solc/solc-js/soljson.js:1:15961)
    at stackTrace (/Users/alex/Projects/solc/solc-js/soljson.js:1:16144)
    at Object.abort (/Users/alex/Projects/solc/solc-js/soljson.js:19:14981)
    at _abort (/Users/alex/Projects/solc/solc-js/soljson.js:1:1240434)
    at cXa (/Users/alex/Projects/solc/solc-js/soljson.js:5:332247)
    at Array.zi (/Users/alex/Projects/solc/solc-js/soljson.js:6:74167)
    at Object.UJb [as dynCall_viii] (/Users/alex/Projects/solc/solc-js/soljson.js:12:322458)
    at invoke_viii (/Users/alex/Projects/solc/solc-js/soljson.js:1:1272342)
    at Array.Xsa (/Users/alex/Projects/solc/solc-js/soljson.js:7:455012)
    at Object.wLb [as dynCall_viiii] (/Users/alex/Projects/solc/solc-js/soljson.js:12:328625)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by axic** [comment]
Wrote a simple wrapper over libsoljson to verify it is not an issue in the C++ code:

```
#include <stdio.h>

typedef void (*CStyleReadFileCallback)(char const* _path, char** o_contents, char** o_error);
char const* compileJSONCallback(char const* _input, int _optimize, CStyleReadFileCallback _readCallback);

void cb(const char* _path, char **o_contents, char **o_error) {
    printf("Importing: %s %x %x\n", _path, o_contents, o_error);

    // strdup to be sure it wont be on the stack/heap, also we don't care about memory leaks :)
    *o_error = strdup("FAIL!");
}

int main(int argc, char *argv[]) {
    const char *input = argv[1];

    printf("%s", compileJSONCallback(input, 0, cb));

    return 0;
}
```

Works with errors:
```
Importing: xxx.sol 39c25a80 39c25a88
{"errors":["cont.sol:1:19: Error: Source not found: FAIL!\nimport \"lib.sol\"; import \"xxx.sol\"; contract x { function g() { L.f(); B.a(); } }\n                  ^---------------^\n"]}
```

Works with leaving contents/error empty.

Works with contents.

--

This leaves me wondering why we don't even get the "File not found." error with an empty callback.

**Comment by axic** [comment]
The problem was this code:

```
                if (readCallback !== undefined && compileJSONCallback !== null)
                        result = compileJSONCallback(JSON.stringify(input), optimise, readCallback);
                if (typeof(input) != typeof('') && compileJSONMulti !== null)
                        result = compileJSONMulti(JSON.stringify(input), optimise);
```

This missing `else` keyword always resulted in running the second case masking any errors in the output.
