### ISSUE TITLE
MODULE_NOT_FOUND with solidity

### ISSUE THREAD

**Issue by godomainz** [ethereum/solc-js#624]
I have a folder structure like below

![structure](https://user-images.githubusercontent.com/34884192/168965317-45429ba3-ccec-4b27-8e92-51ad6d3999c9.png)

this is my compile.ts

```
 import { resolve } from 'path';
import { readFileSync } from 'fs';
import { CompileFailedError, compileSourceString } from 'solc-typed-ast';

const inboxPath = resolve('src/contracts', 'Inbox.sol');
const source = readFileSync(inboxPath, 'utf8');
const compile = async () => {
  try {
    return await compileSourceString(inboxPath, source, 'auto');
  } catch (e) {
    if (e instanceof CompileFailedError) {
      console.error('Compile errors encountered:');
 
      for (const failure of e.failures) {
        console.error(`Solidity compiler ${failure.compilerVersion}:`);
 
        for (const error of failure.errors) {
          console.error(error);
        }
      }
    } else {
      console.error(e as Error);
    }
  }
};

compile().then(result => {
  console.log(result?.data.contracts[`${inboxPath}:Inbox`]);
});
```

below is my package.json

```
{
  "name": "inbox",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "./node_modules/.bin/tsc",
    "runwatch": "./node_modules/.bin/tsc -w",
    "compile": "node dist/compile.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@typechain/truffle-v5": "^8.0.0",
    "truffle": "^5.5.14",
    "ts-node": "^10.7.0",
    "typechain": "^8.0.0",
    "typescript": "^4.6.4",
    "@truffle/hdwallet-provider": "^2.0.8",
    "@types/mocha": "^9.1.1",
    "ganache": "^7.1.0",
    "ganache-cli": "^6.12.2",
    "mocha": "^10.0.0",
    "solc": "^0.8.14",
    "web3": "^1.7.3"
  }
}
```

below is my tsconfig.json

```
{
    "compilerOptions": {
        "outDir": "./dist/",
        "mapRoot": "./dist/",
        "sourceMap": true,
        "lib": ["es5"],
        "module": "CommonJS",
        "target": "ES2018",
        "strict": true,
        "esModuleInterop": true,
        "types": ["@types/node", "@types/mocha"],
        "typeRoots": ["./node_modules/@types", "./types"]
    },
    "include": ["**/*.ts"],
    "exclude": ["node_modules", "build", "cache", "artifacts"],
    "lib": [
        "es2017",
        "dom"
    ]
  }
```

when I run that compile.js file I'm getting below error

```
> inbox@1.0.0 compile F:\Blockchain Projects\ethereum-solidity\section_2\inbox
> node dist/compile.js

Error: Cannot find module './common/helpers'
Require stack:
- F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc\linker.js
- F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc\translate.js
- F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc\wrapper.js
- F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc\index.js
- F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc-typed-ast\dist\compile\kinds\compiler.js
- F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc-typed-ast\dist\compile\kinds\index.js
- F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc-typed-ast\dist\compile\index.js
- F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc-typed-ast\dist\index.js
- F:\Blockchain Projects\ethereum-solidity\section_2\inbox\dist\compile.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc\linker.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'F:\\Blockchain Projects\\ethereum-solidity\\section_2\\inbox\\node_modules\\solc\\linker.js',
    'F:\\Blockchain Projects\\ethereum-solidity\\section_2\\inbox\\node_modules\\solc\\translate.js',
    'F:\\Blockchain Projects\\ethereum-solidity\\section_2\\inbox\\node_modules\\solc\\wrapper.js',
    'F:\\Blockchain Projects\\ethereum-solidity\\section_2\\inbox\\node_modules\\solc\\index.js',
    'F:\\Blockchain Projects\\ethereum-solidity\\section_2\\inbox\\node_modules\\solc-typed-ast\\dist\\compile\\kinds\\compiler.js',
    'F:\\Blockchain Projects\\ethereum-solidity\\section_2\\inbox\\node_modules\\solc-typed-ast\\dist\\compile\\kinds\\index.js',
    'F:\\Blockchain Projects\\ethereum-solidity\\section_2\\inbox\\node_modules\\solc-typed-ast\\dist\\compile\\index.js',
    'F:\\Blockchain Projects\\ethereum-solidity\\section_2\\inbox\\node_modules\\solc-typed-ast\\dist\\index.js',
    'F:\\Blockchain Projects\\ethereum-solidity\\section_2\\inbox\\dist\\compile.js'
  ]
}
undefined
```

how to resolve that error ?

**Comment by cameel** [comment]
Thanks for the report. It has already been reported in #622 though.

Unfortunately solc-js 0.8.14 is broken and we'll be releasing 0.8.15 very soon to fix this. For now the workaround is to use solc-js 0.8.13. Note that while version 0.8.13 of the `solc` npm package comes bundled with a 0.8.13 binary, it's is still compatible with any other binary, in particular with the [0.8.14 wasm binary you can get from solc-bin](https://github.com/ethereum/solc-bin/blob/gh-pages/emscripten-wasm32/solc-emscripten-wasm32-v0.8.14+commit.80d49f37.js).

**Comment by cameel** [comment]
Just a quick update. We actually published the fixed version as [`solc@0.8.14-fixed`](https://www.npmjs.com/package/solc/v/0.8.14-fixed) in npm registry. So no new release of the binary, just solc-js. You can use this new version if you can't just use 0.8.13 with latest binary for some reason.

**Comment by godomainz** [comment]
@cameel nope I'm getting below error. only thing which was worked for me is by adding this   `"solc": "^0.4.17",`
both `0.8.13` and `0.8.14-fixed` did NOT work
```
F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc\wrapper.js:117
            (0, assert_1.default)(typeof callbacks === 'object', 'Invalid callback object specified.');
                                 ^
AssertionError [ERR_ASSERTION]: Invalid callback object specified.
    at runWithCallbacks (F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc\wrapper.js:117:34)
    at compileStandard (F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc\wrapper.js:223:20)
    at Object.compileStandardWrapper [as compile] (F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\solc\wrapper.js:229:20)
    at Object.<anonymous> (F:\Blockchain Projects\ethereum-solidity\section_2\inbox\src\compile.ts:8:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\ts-node\src\index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (F:\Blockchain Projects\ethereum-solidity\section_2\inbox\node_modules\ts-node\src\index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by cameel** [comment]
For anyone who finds this later - the problem above is unrelated to the original issue reported here and was explained in #628.
