### ISSUE TITLE
TypeError: readCallback is not a function at singleCallback  (node_modules/solc/wrapper.js:125:18)

### ISSUE THREAD

**Issue by komus-Israel** [ethereum/solc-js#631]
I'm using solc version 0.8.10

Whenever I try compiling my contract with the import call back, I get that error. I can't compile my contract with the library imported in my contract.

const output = JSON.parse (

    solc.compile(JSON.stringify(input), {import:  findImports(libPath)})
    
)

**Comment by komus-Israel** [comment]
The error

/home/komolehin/Documents/blockchain/solc compiler/single contract compile/node_modules/solc/wrapper.js:154
      throw e;
      ^

TypeError: readCallback is not a function
    at singleCallback (/home/komolehin/Documents/blockchain/solc compiler/single contract compile/node_modules/solc/wrapper.js:125:18)
    at /home/komolehin/Documents/blockchain/solc compiler/single contract compile/node_modules/solc/wrapper.js:84:20
    at <anonymous>:wasm-function[32880]:0xd8b549
    at invoke_viiii (/home/komolehin/Documents/blockchain/solc compiler/single contract compile/node_modules/solc/soljson.js:1:27019144)
    at <anonymous>:wasm-function[25011]:0x921599
    at invoke_viii (/home/komolehin/Documents/blockchain/solc compiler/single contract compile/node_modules/solc/soljson.js:1:27017799)
    at <anonymous>:wasm-function[12252]:0x37d423
    at <anonymous>:wasm-function[24998]:0x91e955
    at invoke_iii (/home/komolehin/Documents/blockchain/solc compiler/single contract compile/node_modules/solc/soljson.js:1:27018787)
    at <anonymous>:wasm-function[24716]:0x8d1ed0
    at invoke_viii (/home/komolehin/Documents/blockchain/solc compiler/single contract compile/node_modules/solc/soljson.js:1:27017799)
    at tb (<anonymous>:wasm-function[41389]:0x1218202)
    at ccall (/home/komolehin/Documents/blockchain/solc compiler/single contract compile/node_modules/solc/soljson.js:1:7697)
    at /home/komolehin/Documents/blockchain/solc compiler/single contract compile/node_modules/solc/soljson.js:1:8087
    at runWithCallbacks (/home/komolehin/Documents/blockchain/solc compiler/single contract compile/node_modules/solc/wrapper.js:151:24)
    at compileStandard (/home/komolehin/Documents/blockchain/solc compiler/single contract compile/node_modules/solc/wrapper.js:207:14)

**Comment by komus-Israel** [comment]
const output = JSON.parse (

solc.compile(JSON.stringify(input), {import:  findImports(libPath)})
)

the error was due to the argument I passed to the findImports function

I removed parameter from function delaration and called the function directly with no argument

solc.compile(JSON.stringify(input), {import:  findImports})

**Comment by cameel** [comment]
> I removed parameter from function delaration and called the function directly with no argument

The key point is the difference between a reference to a function (`findImports`) and a call of that function (`findImports(libPath)`). With the first one you put that function in the `import` field of the object and the compiler will be able to use it as a callback. With the second one you call this function yourself once and put the result in the `import` field. That result is likely not even a function and the error message says just that `TypeError: readCallback is not a function`. The compiler cannot really do anything with it.

By the way, when pasting code please put it in fenced blocks (```` ``` ````). That makes it much easier to find your own comments among all the text.

**Comment by komus-Israel** [comment]
Thank you @cameel
