### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Invalid callback object specified

### ISSUE THREAD

**Issue by vampire-ab** [ethereum/solc-js#668]
Compile.js code: 
`const path = require('path');
const fs = require('fs');
const solc = require('solc');

const inboxPath = path.resolve(__dirname, 'contracts', 'Inbox.sol');
const source = fs.readFileSync(inboxPath, 'utf8');
module.exports = solc.compile(source, 1).contracts[':Inbox'];`

The Error

`"d:\Projects\BlockChain\Inbox\compile.js"
node:assert:400
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Invalid callback object specified.
    at runWithCallbacks (d:\Projects\node_modules\solc\wrapper.js:117:34)
    at compileStandard (d:\Projects\node_modules\solc\wrapper.js:223:20)
    at Object.compileStandardWrapper [as compile] (d:\Projects\node_modules\solc\wrapper.js:229:20)
    at Object.<anonymous> (d:\Projects\BlockChain\Inbox\compile.js:7:21)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}`

**Comment by vampire-ab** [comment]
Covert to the new syntax. Something like this: 
`// const path = require('path');
// const fs = require('fs');
// const solc = require('solc');

// const inboxPath = path.resolve(__dirname, 'contracts', 'Inbox.sol');
// const source = fs.readFileSync(inboxPath, 'utf8');
// module.exports = solc.compile(source, 1).contracts[':Inbox'];
//1 denotes number of contracts we are going to deploy.


const path = require('path');
const fs = require('fs');
const solc = require('solc');



const inboxPath = path.resolve(__dirname, 'contracts', 'Inbox.sol');
const source = fs.readFileSync(inboxPath, 'UTF-8');

var input = {
    language: 'Solidity',
    sources: {
        'Inbox.sol' : {
            content: source
        }
    },
    settings: {
        outputSelection: {
            '*': {
                '*': [ '*' ]
            }
        }
    }
}; 
console.log(JSON.parse(solc.compile(JSON.stringify(input))));


`
