### ISSUE TITLE
"Must provide a file" issue

### ISSUE THREAD

**Issue by resurtm** [ethereum/solc-js#68]
Hello!

Issue I'm experiencing with:
```
$ ./geth attach ipc:/home/resurtm/.ethereum/testnet/geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/v1.4.18-stable-c72f5459/linux/go1.7.1
coinbase: 0x1eded942353420c4ac3f3766ea858dff1f4afdca
at block: 1819615 (Mon, 31 Oct 2016 16:53:09 +06)
 datadir: /home/resurtm/.ethereum/testnet
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> var contract = eth.compile.solidity("contract test { function multiply(uint a) returns(uint d) { return a * 7; } }")
solc: exit status 1
Must provide a file

Specify --help for available options

    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:16

> 
```

Here's my system & software details:
```
$ ./geth version
Geth
Version: 1.4.18-stable-c72f5459
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.7
```
```
$ screenfetch
         _,met$$$$$gg.           resurtm@resurtm-desktop
      ,g$$$$$$$$$$$$$$$P.        OS: Debian testing stretch
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 4.7.0-1-amd64
   ,$$P'              `$$$.      Uptime: 4h 58m
  ',$$P       ,ggs.     `$$b:    Packages: 2565
  `d$$'     ,$P"'   .    $$$     Shell: bash 4.4.0
   $$P      d$'     ,    $$P     Resolution: 1920x1200
   $$:      $$.   -    ,d$$'     DE: XFCE
   $$\;      Y$b._   _,d$P'      WM: Xfwm4
   Y$$.    `.`"Y$$$$P"'          WM Theme: Next
   `$$b      "-.__               GTK Theme: Xfce-basic [GTK2]
    `Y$$                         Icon Theme: Tango
     `Y$$.                       Font: Sans 10
       `$$b.                     CPU: Intel Core i3 CPU 540 @ 3.067GHz
         `Y$$b.                  GPU: GeForce 9500 GT/PCIe/SSE2
            `"Y$b._              RAM: 4598MiB / 5961MiB
                `""""           
```
```
$ uname -a
Linux resurtm-desktop 4.7.0-1-amd64 #1 SMP Debian 4.7.8-1 (2016-10-19) x86_64 GNU/Linux

$ cat /proc/version 
Linux version 4.7.0-1-amd64 (debian-kernel@lists.debian.org) (gcc version 5.4.1 20160904 (Debian 5.4.1-2) ) #1 SMP Debian 4.7.8-1 (2016-10-19)

$ cat /etc/debian_version 
stretch/sid
```
```
$ node --version
v6.9.1

$ npm --version
3.10.8

$ solcjs --version
0.4.3+commit.2353da71.Emscripten.clang

$ solc --version
0.4.3+commit.2353da71.Emscripten.clang

$ ls -la /usr/bin/solc*
lrwxrwxrwx 1 root root  6 Oct 31 16:47 /usr/bin/solc -> solcjs
lrwxrwxrwx 1 root root 31 Oct 31 16:32 /usr/bin/solcjs -> ../lib/node_modules/solc/solcjs
```

Also reported here: https://github.com/ethereum/go-ethereum/issues/2944#issuecomment-257264793

**Comment by chriseth** [comment]
solcjs is not compatible with using it as a compilation backend behind geth. Instead, you can use it directly in nodejs without having to go back and forth to the backend.
